#!/usr/bin/env bash
##############################################################################
##
##  Set name and email required by git for all repositories in the current 
##  directory and it's directly sub-folders.
##
##  Author: Chaobin Wu
##  Email : me@avenwu.net
##
##############################################################################

if [ $# -ne 2 ]; then
    echo "Usage: $0 \"Name\" \"Email@58ganji.com\""
    exit 1
fi

function setUser() {
    git config user.name $1
    git config user.email $2
}

user_name=$1
user_email=$2

echo "Start set user.name = $user_name, user.email = $user_email for all sub git folders under: `pwd`"

if [ -d ".git" ]; then
   echo "Set Current folder: ./"
   setUser $user_name $user_email
fi

for repo in ./*
do
    if [ -d $repo ]; then
        cd $repo
        if [ -d ".git" ]; then
            echo "Found new repo directory: $repo"
            setUser $user_name $user_email
        fi
        cd ../
    fi
done
